<Project>
  <PropertyGroup>
    <!-- Default para todos os projetos abaixo -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Analyzers -->
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>default</AnalysisMode>
    <!-- Quality Gate -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <!-- Builds mais determinísticos -->
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <!-- Enable new .NET 10 Testing Platform for dotnet test -->
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <!-- Remove SonarAnalyzer from docker-compose projects -->
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.dcproj'">
    <GlobalPackageReference Remove="SonarAnalyzer.CSharp" />
  </ItemGroup>
</Project>
