using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using TC.Agro.Analytics.Application.UseCases.Alerts.AcknowledgeAlert;
using TC.Agro.Analytics.Application.UseCases.Alerts.ResolveAlert;
using TC.Agro.Farm.Application.UseCases.Plots.Create;
using TC.Agro.Farm.Application.UseCases.Properties.Create;
using TC.Agro.Farm.Application.UseCases.Sensors.Create;
using TC.Agro.Identity.Application.UseCases.CreateUser;
using TC.Agro.Identity.Application.UseCases.LoginUser;
using TC.Agro.Integration.Tests.Abstractions;
using TC.Agro.SensorIngest.Application.UseCases.CreateReading;
using static TC.Agro.Integration.Tests.Abstractions.BreakGlassE2EFixture;

namespace TC.Agro.Integration.Tests.CrossServiceIntegrationFlows;

/// <summary>
/// E2E tests for the Alert lifecycle: pending → acknowledge → resolve.
/// Verifies that analytics alerts are generated from ingested sensor readings
/// and that the acknowledge/resolve endpoints work correctly.
/// </summary>
public sealed class AlertLifecycleFlowTests : BaseIntegrationTest
{
    public AlertLifecycleFlowTests(CrossServiceIntegrationFixture fixture)
        : base(fixture)
    {
    }

    // ──────────────────────────────────────────
    // Full acknowledge lifecycle
    // ──────────────────────────────────────────

    [Fact]
    public async Task GivenCriticalReading_WhenAlertIsCreated_ThenProducerCanAcknowledgeIt()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var producer = await CreateProducerContextAsync(cancellationToken);
        var (propertyId, plotId, sensorId) = await SetupFarmHierarchyAsync(producer, cancellationToken);

        // Ingest a reading that exceeds the temperature threshold
        await IngestCriticalTemperatureReadingAsync(
            producer, sensorId, temperature: 45, cancellationToken);

        // Wait for alert to be generated by analytics worker
        var alertRow = await Fixture.WaitForAnalyticsAlertAsync(
            sensorId,
            timeout: TimeSpan.FromSeconds(60),
            cancellationToken: cancellationToken);

        alertRow.ShouldNotBeNull("Expected at least one alert to be generated for the critical reading.");
        var alertId = alertRow!.Id;

        // Acknowledge the alert
        var acknowledgeCommand = new AcknowledgeAlertCommand(alertId);

        using var ackResponse = await SendAuthorizedJsonAsync(
            Fixture.AnalyticsClient,
            HttpMethod.Put,
            $"/api/alerts/{alertId}/acknowledge",
            acknowledgeCommand,
            producer.JwtToken,
            cancellationToken);

        ackResponse.StatusCode.ShouldBe(HttpStatusCode.OK, await ackResponse.Content.ReadAsStringAsync(cancellationToken));

        var ackResult = await ackResponse.Content
            .ReadFromJsonAsync<AcknowledgeAlertResponse>(cancellationToken: cancellationToken);

        ackResult.ShouldNotBeNull();
        ackResult!.Id.ShouldBe(alertId);
        ackResult.Status.ShouldBe("Acknowledged");
        ackResult.AcknowledgedBy.ShouldBe(producer.UserId);
    }

    // ──────────────────────────────────────────
    // Full resolve lifecycle
    // ──────────────────────────────────────────

    [Fact]
    public async Task GivenCriticalReading_WhenAlertIsCreated_ThenProducerCanResolveIt()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var producer = await CreateProducerContextAsync(cancellationToken);
        var (_, _, sensorId) = await SetupFarmHierarchyAsync(producer, cancellationToken);

        await IngestCriticalTemperatureReadingAsync(
            producer, sensorId, temperature: 48, cancellationToken);

        var alertRow = await Fixture.WaitForAnalyticsAlertAsync(
            sensorId,
            timeout: TimeSpan.FromSeconds(60),
            cancellationToken: cancellationToken);

        alertRow.ShouldNotBeNull();
        var alertId = alertRow!.Id;

        var resolveCommand = new ResolveAlertCommand(
            AlertId: alertId,
            ResolutionNotes: "Irrigation pump was restarted. Temperature normalized.");

        using var resolveResponse = await SendAuthorizedJsonAsync(
            Fixture.AnalyticsClient,
            HttpMethod.Put,
            $"/api/alerts/{alertId}/resolve",
            resolveCommand,
            producer.JwtToken,
            cancellationToken);

        resolveResponse.StatusCode.ShouldBe(HttpStatusCode.OK,
            await resolveResponse.Content.ReadAsStringAsync(cancellationToken));

        var resolveResult = await resolveResponse.Content
            .ReadFromJsonAsync<ResolveAlertResponse>(cancellationToken: cancellationToken);

        resolveResult.ShouldNotBeNull();
        resolveResult!.Status.ShouldBe("Resolved");
        resolveResult.ResolvedBy.ShouldBe(producer.UserId);
        resolveResult.ResolutionNotes?.ShouldContain("Irrigation pump");
    }

    // ──────────────────────────────────────────
    // Unauthorized access
    // ──────────────────────────────────────────

    [Fact]
    public async Task GivenNoToken_WhenAcknowledgingAlert_ThenAnalyticsReturnsUnauthorized()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var alertId = Guid.NewGuid();

        using var request = new HttpRequestMessage(HttpMethod.Put, $"/api/alerts/{alertId}/acknowledge")
        {
            Content = JsonContent.Create(new AcknowledgeAlertCommand(alertId))
        };

        using var response = await Fixture.AnalyticsClient.SendAsync(request, cancellationToken);

        response.StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    // ──────────────────────────────────────────
    // Alert not found
    // ──────────────────────────────────────────

    [Fact]
    public async Task GivenNonExistentAlert_WhenAcknowledging_ThenAnalyticsReturnsNotFound()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var producer = await CreateProducerContextAsync(cancellationToken);
        var unknownAlertId = Guid.NewGuid();

        using var response = await SendAuthorizedJsonAsync(
            Fixture.AnalyticsClient,
            HttpMethod.Put,
            $"/api/alerts/{unknownAlertId}/acknowledge",
            new AcknowledgeAlertCommand(unknownAlertId),
            producer.JwtToken,
            cancellationToken);

        response.StatusCode.ShouldBe(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task GivenNonExistentAlert_WhenResolving_ThenAnalyticsReturnsNotFound()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var producer = await CreateProducerContextAsync(cancellationToken);
        var unknownAlertId = Guid.NewGuid();

        using var response = await SendAuthorizedJsonAsync(
            Fixture.AnalyticsClient,
            HttpMethod.Put,
            $"/api/alerts/{unknownAlertId}/resolve",
            new ResolveAlertCommand(unknownAlertId, null),
            producer.JwtToken,
            cancellationToken);

        response.StatusCode.ShouldBe(HttpStatusCode.NotFound);
    }

    // ──────────────────────────────────────────
    // Invalid request — empty AlertId
    // ──────────────────────────────────────────

    [Fact]
    public async Task GivenEmptyAlertId_WhenAcknowledging_ThenAnalyticsReturnsBadRequest()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var producer = await CreateProducerContextAsync(cancellationToken);

        // Route with empty Guid causes Bad Request due to route constraint
        using var response = await SendAuthorizedJsonAsync(
            Fixture.AnalyticsClient,
            HttpMethod.Put,
            $"/api/alerts/{Guid.Empty}/acknowledge",
            new AcknowledgeAlertCommand(Guid.Empty),
            producer.JwtToken,
            cancellationToken);

        response.StatusCode.ShouldBeOneOf(
            HttpStatusCode.BadRequest,
            HttpStatusCode.UnprocessableEntity,
            HttpStatusCode.NotFound);
    }

    // ──────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────

    private async Task<ProducerContext> CreateProducerContextAsync(CancellationToken cancellationToken)
    {
        var token = Guid.NewGuid().ToString("N")[..8];
        var password = "Producer@123";

        var createCmd = new CreateUserCommand(
            Name: $"Producer {token}",
            Email: $"producer.alerts.{token}@tcagro.test",
            Username: $"produceralerts{token}",
            Password: password,
            Role: "Producer");

        using var createResp = await Fixture.IdentityClient
            .PostAsJsonAsync("/auth/register", createCmd, cancellationToken);

        createResp.StatusCode.ShouldBe(HttpStatusCode.Created);

        var created = await createResp.Content
            .ReadFromJsonAsync<CreateUserResponse>(cancellationToken: cancellationToken);

        created.ShouldNotBeNull();

        using var loginResp = await Fixture.IdentityClient
            .PostAsJsonAsync("/auth/login", new LoginUserCommand(createCmd.Email, password), cancellationToken);

        loginResp.StatusCode.ShouldBe(HttpStatusCode.OK);

        var login = await loginResp.Content
            .ReadFromJsonAsync<LoginUserResponse>(cancellationToken: cancellationToken);

        login!.JwtToken.ShouldNotBeNullOrWhiteSpace();

        await Fixture.WaitForFarmOwnerSnapshotAsync(created!.Id, TimeSpan.FromSeconds(45), cancellationToken: cancellationToken);
        await Fixture.WaitForAnalyticsOwnerSnapshotAsync(created.Id, TimeSpan.FromSeconds(45), cancellationToken: cancellationToken);

        return new ProducerContext(created.Id, login.JwtToken, token);
    }

    private async Task<(Guid PropertyId, Guid PlotId, Guid SensorId)> SetupFarmHierarchyAsync(
        ProducerContext producer,
        CancellationToken cancellationToken)
    {
        var propCmd = new CreatePropertyCommand(
            Name: $"Alert Test Property {producer.Token}",
            Address: "Alert Test Road, km 01",
            City: "Ribeirao Preto",
            State: "SP",
            Country: "Brazil",
            AreaHectares: 50.0,
            Latitude: -21.1767,
            Longitude: -47.8208);

        using var propResp = await SendAuthorizedJsonAsync(
            Fixture.FarmClient, HttpMethod.Post, "/api/properties",
            propCmd, producer.JwtToken, cancellationToken);

        propResp.StatusCode.ShouldBe(HttpStatusCode.Created);
        var property = await propResp.Content
            .ReadFromJsonAsync<CreatePropertyResponse>(cancellationToken: cancellationToken);
        property.ShouldNotBeNull();

        var cropTypeCatalogId = await Fixture.EnsureFarmSystemCropCatalogAsync("Corn", cancellationToken);

        var plotCmd = new CreatePlotCommand(
            PropertyId: property!.Id,
            Name: $"Alert Plot {producer.Token}",
            CropType: "Corn",
            AreaHectares: 20.0,
            Latitude: -21.1775,
            Longitude: -47.8103,
            BoundaryGeoJson: "{\"type\":\"Polygon\",\"coordinates\":[[[-47.811,-21.178],[-47.809,-21.178],[-47.809,-21.176],[-47.811,-21.176],[-47.811,-21.178]]]}",
            PlantingDate: DateTimeOffset.UtcNow.AddDays(-10),
            ExpectedHarvestDate: DateTimeOffset.UtcNow.AddDays(90),
            IrrigationType: "Drip Irrigation",
            AdditionalNotes: "Alert test plot",
            CropTypeCatalogId: cropTypeCatalogId);

        using var plotResp = await SendAuthorizedJsonAsync(
            Fixture.FarmClient, HttpMethod.Post, "/api/plots",
            plotCmd, producer.JwtToken, cancellationToken);

        plotResp.StatusCode.ShouldBe(HttpStatusCode.Created);
        var plot = await plotResp.Content
            .ReadFromJsonAsync<CreatePlotResponse>(cancellationToken: cancellationToken);
        plot.ShouldNotBeNull();

        var sensorCmd = new CreateSensorCommand(
            PlotId: plot!.Id,
            Type: "Temperature",
            Label: $"Alert Sensor {producer.Token}",
            OwnerId: producer.UserId);

        using var sensorResp = await SendAuthorizedJsonAsync(
            Fixture.FarmClient, HttpMethod.Post, "/api/sensors",
            sensorCmd, producer.JwtToken, cancellationToken);

        sensorResp.StatusCode.ShouldBe(HttpStatusCode.Created);
        var sensor = await sensorResp.Content
            .ReadFromJsonAsync<CreateSensorResponse>(cancellationToken: cancellationToken);
        sensor.ShouldNotBeNull();

        // Wait for sensor snapshot to be propagated to analytics
        await Fixture.WaitForAnalyticsSensorSnapshotAsync(
            sensor!.Id, TimeSpan.FromSeconds(45), cancellationToken: cancellationToken);

        return (property.Id, plot.Id, sensor.Id);
    }

    private async Task IngestCriticalTemperatureReadingAsync(
        ProducerContext producer,
        Guid sensorId,
        double temperature,
        CancellationToken cancellationToken)
    {
        var command = new CreateReadingCommand(
            SensorId: sensorId,
            Timestamp: DateTime.UtcNow,
            Temperature: temperature,          // Above threshold (35°C) → triggers alert
            Humidity: 55.0,
            SoilMoisture: 40.0,
            Rainfall: null,
            BatteryLevel: 85.0);

        using var response = await SendAuthorizedJsonAsync(
            Fixture.SensorIngestClient, HttpMethod.Post, "/api/readings",
            command, producer.JwtToken, cancellationToken);

        response.StatusCode.ShouldBe(HttpStatusCode.OK,
            await response.Content.ReadAsStringAsync(cancellationToken));
    }

    private static Task<HttpResponseMessage> SendAuthorizedJsonAsync<TPayload>(
        HttpClient client,
        HttpMethod method,
        string route,
        TPayload payload,
        string jwtToken,
        CancellationToken cancellationToken)
    {
        var request = new HttpRequestMessage(method, route)
        {
            Content = JsonContent.Create(payload)
        };
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", jwtToken);
        return client.SendAsync(request, cancellationToken);
    }

    private sealed record ProducerContext(Guid UserId, string JwtToken, string Token);
}
